# Generated by Django 4.0.1 on 2022-01-12 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(db_column='department_name', max_length=500, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'department',
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='full_name', max_length=500, verbose_name='Nombre completo')),
                ('dui', models.CharField(db_column='dui', max_length=50, verbose_name='DUI')),
                ('phone_number', models.CharField(blank=True, db_column='phone_number', max_length=100, null=True, verbose_name='Teléfono')),
                ('birth_date', models.DateField(blank=True, db_column='birth_date', null=True, verbose_name='Fecha de nacimiento')),
                ('address', models.TextField(blank=True, db_column='address', null=True, verbose_name='Dirección')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'employee',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(db_column='gender_name', max_length=500, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Generos',
                'db_table': 'cat_gender',
                'ordering': ['gender_name'],
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_unit_name', models.CharField(db_column='org_unit_name', max_length=500, verbose_name='Unidad organizativa')),
            ],
            options={
                'verbose_name': 'Unidad organizativa',
                'verbose_name_plural': 'Unidades organizativas',
                'db_table': 'cat_org_unit',
                'ordering': ['org_unit_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(db_column='position_name', max_length=500, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cat_position',
                'ordering': ['position_name'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(db_column='profession_name', max_length=500, verbose_name='Profesión')),
            ],
            options={
                'verbose_name': 'Profesión',
                'verbose_name_plural': 'Profesiones',
                'db_table': 'cat_profession',
                'ordering': ['profession_name'],
            },
        ),
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type_name', models.CharField(db_column='vaccine_type_name', max_length=500, verbose_name='Nombre de vacuna')),
            ],
            options={
                'verbose_name': 'Tipo de vacuna',
                'verbose_name_plural': 'Tipos de vacuna',
                'db_table': 'cat_vaccine_type',
                'ordering': ['vaccine_type_name'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousCovidCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspicion_start_date', models.DateField(blank=True, db_column='suspicion_start_date', null=True, verbose_name='Fecha de inicio incapacidad por sospecha')),
                ('suspicion_end_date', models.DateField(blank=True, db_column='suspicion_end_date', null=True, verbose_name='Fecha de finalización incapacidad por sospecha')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vaccination.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Caso COVID sospechoso',
                'verbose_name_plural': 'Casos COVID sospechosos',
                'db_table': 'suspicious_covid_case',
                'ordering': ['suspicion_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_name', models.CharField(db_column='municipality_name', max_length=500, verbose_name='Municipio')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vaccination.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipality',
                'ordering': ['department'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vaccination.gender', verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='employee',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vaccination.municipality', verbose_name='Departamento / Municipio'),
        ),
        migrations.AddField(
            model_name='employee',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vaccination.orgunit', verbose_name='Unidad organizativa'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vaccination.position', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vaccination.profession', verbose_name='Profesión'),
        ),
        migrations.CreateModel(
            name='ConfirmedCovidCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhability_start_date', models.DateField(blank=True, db_column='inhability_start_date', null=True, verbose_name='Fecha de inicio incapacidad')),
                ('inhability_end_date', models.DateField(blank=True, db_column='inhability_to_date', null=True, verbose_name='Fecha de finalización incapacidad')),
                ('hospitalized', models.BooleanField(blank=True, db_column='hospitalized', null=True, verbose_name='Hospitalizado')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vaccination.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Caso COVID confirmado',
                'verbose_name_plural': 'Casos COVID confirmados',
                'db_table': 'confirmed_covid_case',
                'ordering': ['inhability_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booster_date', models.DateField(blank=True, db_column='booster_date', null=True, verbose_name='Fecha de dosis')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vaccination.employee', verbose_name='Empleado')),
                ('vaccine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vaccination.vaccinetype', verbose_name='Tipo de vacuna')),
            ],
            options={
                'verbose_name': 'Dosis',
                'verbose_name_plural': 'Dosis',
                'db_table': 'booster',
                'ordering': ['booster_date'],
            },
        ),
    ]
